# Site settings
title: Jerry Fleurival Web Projects
description: Showing my best and awesome work.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jerry Fleurival
user_description: This webpage contains web design and development projects.
user_title: Web Developer
email: contact@jerryfleurival.com
github_username: jerryfleurival
linkedin_username: jerryfleurival
youtube_username: jerryfleurival

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
